name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: KDA-sparkle
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Commit and Push Snake Animation
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "🐍 Updated GitHub contribution snake animation"
          git push
