name: Generate Yandere Glitch Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Met à jour toutes les 6 heures
  push:
  workflow_dispatch:

jobs:
  generate-glitch-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Yandere Glitch SVG
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="120">
            <style>
              @keyframes glitch {
                0% { transform: translate(0, 0); }
                20% { transform: translate(-2px, 2px); }
                40% { transform: translate(2px, -2px); }
                60% { transform: translate(-2px, -2px); }
                80% { transform: translate(2px, 2px); }
                100% { transform: translate(0, 0); }
              }
              text {
                font-size: 30px;
                text-anchor: middle;
                dominant-baseline: middle;
                font-family: "Courier New", monospace;
                animation: glitch 0.8s infinite alternate;
              }
            </style>
            <rect width="100%" height="100%" fill="black"/>
            <text x="50%" y="30%" fill="red">YANDERE MODE ACTIVATED</text>
            <text x="50%" y="60%" fill="white">You can’t escape me...</text>
            <text x="50%" y="90%" fill="pink">I see everything...</text>
          </svg>' > yandere-glitch-text.svg

      - name: Commit and Push SVG
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add yandere-glitch-text.svg
          git commit -m "🔪 Updated Yandere glitch animation"
          git push
