name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  # Exécute toutes les 12 heures
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # PAT avec les permissions nécessaires
          user: KDA-sparkle
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          config_display: large
          config_padding: 10%
          
          # Plugins activés
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          
          plugin_lines: yes
          plugin_traffic: yes
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          plugin_followup: yes
          plugin_followup_sections: repositories, users
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
