name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  # Toutes les 12 heures
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token par défaut
          user: KDA-sparkle
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Paris
          filename: github-metrics.svg
          
          # Plugins publics sécurisés
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          # Statistiques basiques
          repositories_batch: 10
          repositories_limit: 4
          repositories_affiliations: owner
          config_display: large
